constantinpape/torch-em

torch_em/trainer/wandb_logger.py
necessary due to multiple wand.log calls per step
=> specify log step in wand.log calls

environment_cpu.yaml, environment_gpu.yaml, test/transform/test_generic.py, torch_em/transform/__init__.py, torch_em/transform/generic.py
Not sure about the preferred way to add a dimension agnostic transformation.
This `class Tile(torch.nn.Module)` implementation does not inherite from a kornia class (as there is no public common base class for 2D/3D), but is compatible with them.. maybe there should be an abstract base class for these cases...
=> add a generic Tile transformation; like numpy.tile

torch_em/segmentation.py, torch_em/trainer/wandb_logger.py, torch_em/transform/augmentation.py
Improve offline wandb run name (no colon). Now the resulting file path is also valid on windows.
hitchhiking on this PR: `import torch.utils.data` for `torch.utils.data.DataLoader`  (previously it was only `import torch`)
=> Wandb logger

torch_em/trainer/default_trainer.py
#21 wasn't fully done after all 🤦 
trainer.checkpoint_folder needs to be accessed after logger init
due to the logger potentially setting the name
=> fix DefaultTrainer checkpoint_folder

test/data/test_segmentation_dataset.py, test/test_segmentation.py, torch_em/data/segmentation_dataset.py, torch_em/segmentation.py, torch_em/util/test.py
This PR implements training with channels in the raw data. This only works for data with channel first (torch-native) and if `ndim=2/3, with_channels=True` is passed explicitly to `torch_em.default_segmentation_loader` / `torch_em.default_segmentation_dataset`.
~~The changes are fairly small, but I am not sure if this invalidates old checkpoints (because the `SegmentationDataset` is pickled within them); will check later before merging this.~~
Edit: checked, checkpoints can still be loaded
cc @FynnBe
=> Support training with channels

torch_em/data/pseudo_label_dataset.py, torch_em/shallow2deep/shallow2deep_model.py
adapt order of transform to work for pseudo-label training (rf_predictor takes raw (not-normalized) input).
add default values to load_rf since otherwise torch.load in trainer throws error when trying to load from checkpoint.
=> fix bugs for pseudo-label learning

torch_em/segmentation.py, torch_em/trainer/default_trainer.py, torch_em/trainer/wandb_logger.py
- optional `id_` argument for trainer (fallback to `name`)
- the logger might set `id_` if not given (if `id_`  is None)
allows to let the logger (e.g. `WandbLogger`) to set a run id to save checkpoints of independent runs in their respective folders, etc...
=> Allow logger to generate a (run) id

torch_em/trainer/wandb_logger.py
If I understand correctly torch-em considers metric values to be ordered as loss values (smaller is better)... 
If so, then this PR fixes a bug for logging the best metric so the wandb summary.
=> fix best_metric < worst_metric

torch_em/transform/augmentation.py
Leads to error when input is torch.Tensor. Never recognized because inputs were ususally numpy arrays.
=> fix typo in augmentations

torch_em/shallow2deep/prepare_shallow2deep.py
When set manually via filter_config, there have been some issues with filters of type `structureTensorEigenvalues` since they require the additional argument `outerScale`.
```python
raw = np.random.rand(32, 256, 256)
filters_and_sigmas = _get_filters(3, [('hessianOfGaussianEigenvalues', (3., 1.25*3, 1.25*3))])
features = _apply_filters(raw, filters_and_sigmas)
print(features.shape)
```
--> works fine
```python
filters_and_sigmas = _get_filters(3, [('structureTensorEigenvalues', (3., 1.25*3, 1.25*3))])
features = _apply_filters(raw, filters_and_sigmas)
print(features.shape)
```
--> throws the following error
```
---------------------------------------------------------------------------
File ~/torch-em/torch_em/shallow2deep/prepare_shallow2deep.py:222, in _apply_filters(raw, …
```
=> ensure correct behaviour of filters when set manually

experiments/shallow2deep/em-boundaries/train_isbi_2d.py, experiments/shallow2deep/em-mitochondria/.gitignore, experiments/shallow2deep/em-mitochondria/README.md, experiments/shallow2deep/em-mitochondria/evaluation.py, experiments/shallow2deep/em-mitochondria/export_enhancer.py, experiments/shallow2deep/em-mitochondria/train_vnc_2d.py, experiments/shallow2deep/em-mitochondria/train_vnc_direct.py, experiments/shallow2deep/em-mitochondria/visualize_rfs.py, torch_em/shallow2deep/__init__.py, torch_em/shallow2deep/prepare_shallow2deep.py, torch_em/shallow2deep/shallow2deep_eval.py
Hey @JonasHell @k-dominik, @akreshuk
I have implemented a training routine for random forests for shallow 2 deep here that trains RFs in stages, and selects the training examples for each stage by taking the worst predictions from forests from the previous stage, similar to what we discussed during the retreat. This is implemented with `prepare_shallow2deep_advanced` by adding a `sampling_strategy` parameter that enables customizing the sampling of random forest training samples. (And using the strategy described above by default).
I will train a RF for mito segmentation based on this shortly and share it, to see if it improves results. And if you have other sampling strategies (e.g. sampling scribbles instead of points), we could eventually think about adding them here.
In more detail, …
=> Implement advanced rf training for s2d

torch_em/shallow2deep/prepare_shallow2deep.py
Current implementation looks quite complicated. Unfortunately, the idea is not compatible with your `_score_based_points()`. But maybe there still some room to improve my implementation...
=> add worst_tiles sampling

torch_em/shallow2deep/prepare_shallow2deep.py
I think there is no additional check needed since `_apply_filters()` already checks if a function with this name exists, and it is called before `_serialize_feature_config()`
=> adapt _serialize_feature_config() to work with strings

test/util/test_imageio.py, torch_em/util/image.py
closes #92
I have added test but not executed them. I do not see why test are not executed on pull requests. Maybe you need to approve the run.
=> Use tifffile to read compressed tif files 

test/data/test_image_collection_dataset.py, torch_em/data/image_collection_dataset.py
Add heuristics to allow to channel ais into being the first axis. 
For better compatibility with preview data in napari, for example.
=> When loading data for train allow to read data that has channel on first position

torch_em/transform/raw.py
- updated all the default values to a more reasonable range
- everything works for [0, 1]-range images
- add GaussianBlur class to allow for random kernel_size and sigma
=> provide reasonable default values for augmentations

torch_em/transform/raw.py
I think the default augementations were still to strong (especially if multiple augmentation were combined), so I adjusted it. Also, I replaced the additive poisson noise with a data-dependent version. After a long discussion with @FynnBe I realized that this makes more sense. Otherwise it is hard to find a default lambda that works regardless of the kind of data (normalized to [0, 1] vs actual photon counts).
=> Augmentations

test/loss/test_loss_wrapper.py, torch_em/loss/wrapper.py
I cleaned my git repo. Unfortunately, renaming of branches leads to the closing of connected PRs. So I opened a new one. To not loose the old discussion, I link the old PR [here](https://github.com/constantinpape/torch-em/pull/90).
=> implement gradient masking with cropping - new PR

torch_em/util/prediction.py
I am cleaning up my code. At some point I added these additional args to adjust the tqdm output because I called this function repeatedly and this resulted in an ugly output. However, I am not sure if you want to keep the changes. Just wanted to make sure they are documented somewhere.
=> add args to adjust tqdm output

experiments/probabilistic_domain_adaptation/livecell/common.py, experiments/probabilistic_domain_adaptation/livecell/unet_adamt.py, experiments/probabilistic_domain_adaptation/livecell/unet_source.py
- updated the patch shape : (512, 512) -> (256,256)
- added `save_root` argument in the `evaluate_source_model` function to route the checkpoints from desired path
=> Update Prob-DA Source UNet Parameters

experiments/probabilistic_domain_adaptation/README.md, experiments/probabilistic_domain_adaptation/livecell/common.py, experiments/probabilistic_domain_adaptation/livecell/unet_adamatch.py, experiments/probabilistic_domain_adaptation/livecell/unet_adamt.py, experiments/probabilistic_domain_adaptation/livecell/unet_fixmatch.py, experiments/probabilistic_domain_adaptation/livecell/unet_mean_teacher.py, torch_em/self_training/__init__.py, torch_em/self_training/fix_match.py, torch_em/self_training/mean_teacher.py
- Mean-Teacher training parameters updated
- AdaMT training parameters updated
=> Update Mean-Teacher and FixMatch Self-Training Scheme(s)

experiments/probabilistic_domain_adaptation/livecell/common.py, experiments/probabilistic_domain_adaptation/livecell/punet_source.py, torch_em/self_training/__init__.py, torch_em/self_training/loss.py, torch_em/self_training/mean_teacher.py, torch_em/self_training/probabilistic_unet_trainer.py
- PUNet Source Training Workflow
> (TODO: evaluation script will follow)
=> Add 2D Probabilistic UNet Training Setup

experiments/probabilistic_domain_adaptation/livecell/common.py, experiments/probabilistic_domain_adaptation/livecell/punet_adamt.py, experiments/probabilistic_domain_adaptation/livecell/punet_mean_teacher.py, experiments/probabilistic_domain_adaptation/livecell/unet_adamt.py, experiments/probabilistic_domain_adaptation/livecell/unet_fixmatch.py, torch_em/self_training/__init__.py, torch_em/self_training/loss.py, torch_em/self_training/pseudo_labeling.py
Adding the Probabilistic Domain Adaptation Frameworks (+ rerun) :
- Mean-Teacher (Separate) ✅ (results in)
- Mean-Teacher (Joint) ✅ (training-in-progress)
- (WIP) FixMatch (both joint and separate)
=> Add Probabilistic Self-Training Approaches

experiments/probabilistic_domain_adaptation/livecell/punet_adamatch.py, experiments/probabilistic_domain_adaptation/livecell/punet_fixmatch.py
- FixMatch Separate Training Setup
- FixMatch Joint (AdaMatch) Training Setup
- Updating checkpoint path for Mean-Teacher Joint Trainings (AdaMT)
=> Add FixMatch-based Probabilistic Domain Adaptation Setups

experiments/vision-transformer/unetr/README.md, experiments/vision-transformer/unetr/cremi_unetr.py, experiments/vision-transformer/unetr/initialize_with_sam.py, experiments/vision-transformer/unetr/livecell_unetr.py, torch_em/model/__init__.py, torch_em/model/unetr.py
I checked up for UNETR, and tried to fix the overalls (one final thing is still missing - the switch between ViT models)
To address some previous questions - 
- We do the preprocessing for the inputs to make sure that the dimensions are as SAM's ViT appreciates (1024 * 1024)
- The initialization of SAM works now (the parameters are getting updated)
- Added training script for Cremi (and updated for LiveCell)
In general, UNETR models can now be called from two obvious functions super easily (`from torch_em.model import build_unetr_with_sam_initialization, build_unetr_without_sam_initialization`) (not 100% of the nomenclature though)
=> Fixes and Updates for UNETR

torch_em/data/datasets/__init__.py, torch_em/data/datasets/pannuke.py
- Adding the dataloader for the [PanNuke](https://warwick.ac.uk/fac/cross_fac/tia/data/pannuke
) dataset (histopathology domain)
=> Add PanNuke Dataloader

scripts/datasets/.gitignore, scripts/datasets/check_bcss.py, torch_em/data/datasets/__init__.py, torch_em/data/datasets/bcss.py, torch_em/data/datasets/util.py
(WIP) Implementation for the Breast Cancer Semantic Segmentation dataset.
(TODOs):
- ~need to fix data download using `gdown` (download limit for folders is upto 50 files, need to take care of that)~ warning raised
=> Add BCSS Dataset

scripts/datasets/check_monuseg.py, torch_em/data/datasets/__init__.py, torch_em/data/datasets/monuseg.py, torch_em/data/datasets/util.py
- Added processing for the monuseg inputs (including xml to numpy array conversion) (kept the expected directory formats consistent)
- (WIP) Add the test split
- (TODO) Check the organ splits from the challenge's metadata and make those splits (mentioned in TODOs)
=> Updates to MoNuSeg

experiments/vision-transformer/unetr/livecell_unetr.py, torch_em/util/segmentation.py
- Add two watershed segmentation (from components and from maxima of distance transform)
- (WIP) Test them on UNETR predictions on LiveCell
=> Add Watershed Segmentation Functionality

torch_em/data/datasets/lizard.py
Hi @constantinpape,
- The links to the lizard dataset download have some isses
- They download some irregular zip file, and it's not available to download from the webpage as well (maybe they have taken it down?)
- Current fix: downloading the zip from kaggle (there's a dataset uploaded in the exact same manifolds - just downloading the zip files as it is does the trick to work with the current dataloader)
- (maybe for later) I will adapt the kaggle cli to torch_em to download datasets from kaggle as well
- Raising a warning to user when request download
=> Raise warning for Lizard data download

scripts/datasets/check_bcss.py, torch_em/data/datasets/bcss.py
- Making train / val split using random splitting on the fly, and test data is pre-defined in a global list, which has exclusive 10% (of the entire data) patient slides.
=> Add splits for BCSS dataset

experiments/vision-transformer/unetr/initialize_with_sam.py, torch_em/model/__init__.py, torch_em/model/unetr.py, torch_em/model/vit.py
This PR refactors the vision transformers in models in a separate module, as well as implements the vision transformer from MAEs (to make use of their pretrained models).
=> Add ViT-MAE and Refactor ViT(s)

experiments/vision-transformer/unetr/livecell/common.py, experiments/vision-transformer/unetr/livecell/livecell_all_unetr.py
This PR takes care of the minor updates with regards to updating UNETR for the latest version.
=> Fix UNETR Model for LIVECell

test/model/test_unetr.py, torch_em/model/unetr.py
to enable consistency with SAM and use full encoder input shape rather than naively padding.
This is still a draft to discuss what the best default is and how we can best integrate this with previous code.
=> Update UNETR to enable resize to longest side

torch_em/util/grid_search.py, torch_em/util/segmentation.py
pending https://github.com/computational-cell-analytics/micro-sam/pull/300
=> Implement grid-search for distance based segmentation

scripts/datasets/check_siim_acr.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/siim_acr.py, torch_em/data/datasets/util.py, torch_em/data/image_collection_dataset.py, torch_em/transform/generic.py
This is a dataset for segmenting pneumothorax in chest x-rays.
=> Add SIIM ACR Pneumothorax dataset

torch_em/model/unet.py
I am restoring the old default for the normalization layer, given that tracking the stats leads to a decrease in segmentation quality.
cc @anwai98
=> Restore old norm layer defaults

scripts/datasets/medical/check_piccolo.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/piccolo.py, torch_em/data/datasets/util.py
This is a dataset for segmentation of polyps in narrow band imaging colonoscopy images. Will potentially be nice for OOD investigation. GTG from my side. Thanks!
=> Add PICCOLO dataset

torch_em/model/unetr.py
Hi @constantinpape,
This is linked to `micro-sam` as well. Since the `OldDefault` is not supported with the latest updates, this needs to be changed (else loading models fails with the missing norm layer configuration)
=> Minor fix to UNETR mini-batch norm

scripts/datasets/medical/check_toothfairy.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/toothfairy.py
=> Add Toothfairy dataset

torch_em/data/datasets/medical/papila.py
=> Minor fix to adapt label conversion scripts for papila

torch_em/transform/label.py
[issue](https://github.com/constantinpape/torch-em/issues/320)
=> added label transform class encorporating min_size of labels

torch_em/data/datasets/electron_microscopy/mitoem.py
The download seemed to fail via blob on HF, moved it to resolve (as suggested by HF download link), seems to work now. GTG from my side!
=> Minor update to MitoEM rat sample labels download link

torch_em/transform/generic.py
Hi @constantinpape,
I decided to extend our transform, to support re-transforming the reshaped inputs to the original size. I decided upon this design in favor of avoiding to store different shapes to unpad and resize the transformed inputs. Let me know if you think otherwise. Thanks!
=> Extend functionality to obtain original inputs from resized inputs

torch_em/data/datasets/__init__.py, torch_em/util/util.py
I think this addition would make the model loading quite flexible, regardless of using the directory where checkpoints are stored or directly the checkpoints.
=> Minor update to load_model: Support loading directly from checkpoint

torch_em/segmentation.py, torch_em/self_training/fix_match.py, torch_em/self_training/mean_teacher.py, torch_em/self_training/probabilistic_unet_trainer.py, torch_em/trainer/default_trainer.py, torch_em/trainer/spoco_trainer.py
This PR adds `non_blocking=True` to tensor pins to `cuda` to enable asynchronous copies of objects, leading to a minor speed up.
NOTE: This only works when items originate from pinned memory, i.e. works only when the argument `pin_memory=True` is passed to the dataloader.
Reference: https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-pinning
This should in theory speed up respective trainings as well. GTG from my side. Thanks!
Closes https://github.com/constantinpape/torch-em/issues/356.
=> Set non_blocking to True for tensor device allocation

torch_em/data/datasets/light_microscopy/dynamicnuclearnet.py
This PR adds the function `get_dynamicnuclearnet_data` to make the data unzipping process exclusive (i.e. to extend support for verifying the data's existence exclusively without touching the dataset). GTG from my side!
=> Minor update to DynamicNuclearNet dataset

scripts/datasets/histopathology/check_lizard.py, torch_em/data/datasets/histopathology/lizard.py
Resolves https://github.com/constantinpape/torch-em/issues/343
This PR updates the following:
- Moves the download to kaggle api-based function supported by `torch-em`
- Adds docstring to the functions
- Refactors download functionality to move it under `get_lizard_data` function.
=> Update lizard dataset - change download to kaggle api

torch_em/self_training/mean_teacher.py
=> added sampler logic to mean_teacher

scripts/datasets/histopathology/check_lynsec.py, torch_em/data/datasets/histopathology/__init__.py, torch_em/data/datasets/histopathology/lynsec.py
This PR adds a new dataset for nucleus segmentation in H&E and IHC images. GTG from my side!
=> Add LyNSeC data

scripts/datasets/light_microscopy/check_bitdepth_nucseg.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/arvidsson.py, torch_em/data/datasets/light_microscopy/bitdepth_nucseg.py
This PR adds DAPI-stained fluorescence microscopy images for nuclei segmentation. GTG from my side!
=> Add BitSeg NucSeg dataset

scripts/datasets/histopathology/check_cryonuseg.py, torch_em/data/datasets/histopathology/cryonuseg.py
This PR takes care of a minor update in CryoNuSeg dataset.
(TLDR: 'labels masks modify' are the instance labels we should use - as the overlapping nuclei are dealt with over there without letting them merge with artifacts)
I'll go ahead and merge this once the tests pass!
=> Minor update to cryonuseg dataset

torch_em/data/datasets/medical/oimhs.py
This PR takes care of a minor fix to OIMHS data split preparation (i.e. previously, we hard-coded the absolute paths to the directory, which fails in case the path to data changes).
This should be fixed now. I'll go ahead and merge this once the tests pass!
=> Minor fix to OIMHS dataset

torch_em/data/datasets/medical/siim_acr.py
This PR takes care of a minor inconsistency (which was handled with samplers as expected, however is hard to work with benchmarking other methods). I decided to make it consistent and consider only inputs valid which have any annotations (for reference, a huge portion of images do not have foreground labels).
I'll go ahead and merge this once the tests pass!
=> Ignore inputs with empty labels for SIIM ACR dataset

torch_em/data/datasets/medical/cbis_ddsm.py
This PR takes care of an additional (optional) argument to avoid getting image-label pairs with mismatching shapes. This is GTG from my side. I'll go ahead and merge this once the tests pass!
=> Add argument to get expected image-label pairs for CBIS DDSM data

scripts/datasets/histopathology/check_lizard.py, torch_em/data/datasets/histopathology/lizard.py
Superseeds and closes https://github.com/constantinpape/torch-em/pull/433.
This PR takes care of creating splits for train-val-test (provided by the data curators) (thanks for @titusgriebel for taking care of this).
PS @titusgriebel: I decided to map splits 1, 2, 3 to `train`, `val` and `test` split names, respectively (with them respectively having 70, 70 and 98 samples). We can discuss if you think another mapping makes more sense. For now, let's stick to this for simplicity. Changing the split maps should be straight forward.
I'll go ahead and merge this once the tests pass.
=> Make splits for lizard dataset

torch_em/data/datasets/histopathology/cpm.py
This PR takes care of a minor fix to check for pre-downloaded zipfile to perform preprocessing. I'll merge this once the tests pass!
=> Minor fix to check for zipfile in CPM dataset

torch_em/data/datasets/histopathology/tnbc.py
This PR takes care of a super minor fix in preprocessing TNBC inputs. I previously assumed that all images had 4 channels, but that does not seem to be true. I added a check now on top to remove the alpha channel from images where it is not relevant. I'll merge this once the tests pass!
=> Minor fix to removing alpha channel in TNBC data

torch_em/data/datasets/light_microscopy/cvz_fluo.py, torch_em/data/datasets/util.py, torch_em/util/debug.py
This PR adds supports for data download hosted on `synapse` (ttps://www.synapse.org). GTG from my side!
And closes https://github.com/constantinpape/torch-em/issues/447.
=> Add download functionality support for `synapse` hosted datasets

torch_em/data/datasets/medical/osic_pulmofib.py
This PR takes care of a minor refactor to OSIC PulmoFib dataset. I'll merge this once the tests pass!
=> Minor update to OSIC PulmoFib preprocessing scripts

scripts/datasets/histopathology/check_glas.py, torch_em/data/datasets/histopathology/__init__.py, torch_em/data/datasets/histopathology/glas.py
Superseeds and closes https://github.com/constantinpape/torch-em/pull/473.
This PR adds a new dataset for gland segmentation in histopathology (relevant for our current round of experiments).
=> Add GlaS dataset

torch_em/data/datasets/medical/busi.py
Minor fix to BUSI data paths' return type (this broke the doc builds). I'll merge this!
=> Fix return type for BUSI data paths

torch_em/data/datasets/light_microscopy/arvidsson.py, torch_em/data/datasets/light_microscopy/bitdepth_nucseg.py, torch_em/data/datasets/light_microscopy/brifiseg.py
This PR takes care of a few minor fixes to LM datasets. I'll merge this once the tests pass!
=> Minor updates to LM datasets

torch_em/util/util.py
This PR fixes the random color generator for plotting instance segmentation. I'll merge this once the tests pass!
cc: @constantinpape
=> Minor fix to generate color maps for instances with no background

scripts/datasets/electron_microscopy/check_cellmap.py, torch_em/data/datasets/electron_microscopy/cellmap.py
This PR takes care of major fixes to CellMap dataset by checking for matching scales per resolution level to get the ground truth mask crops and corresponding raw crops.
Works now as expected (tested on the cases reported by @lufre1). GTG from my side!
@constantinpape let me know how it looks!
=> Fix CellMap dataset

torch_em/data/datasets/electron_microscopy/cellmap.py
This PR closes https://github.com/constantinpape/torch-em/issues/511 by removing the test crops from the manifest, as they do not have ground truth masks, hence we do not want them for now.
=> Minor fix to CellMap data - remove test crops

test/model/test_unetr.py, torch_em/model/unetr.py
This PR takes care of passing the `use_conv_transpose` to the corresponding upsampling blocks, to ensure we do upsampling (instead of conv. transpose) properly.
I added an exclusive test to check for both cases as well now!
=> Fix UNETR decoder upsampling

torch_em/data/segmentation_dataset.py
This PR takes care of a super minor update to make finding the desired length of samples subjected to the original shape of input vs desired patch shape.
We should use `ceil` here instead of classic integer casting, as the product of the shape divisions per dimension for a larger desired patch shape might be <1 (even go lower than 0.5, where rounding stops working and returns `n_samples=0` and the segmentation dataset returns nothing (which shouldn't be the case as for smaller data crops with larger patch shape request should be handled as we allow padding the volume to the patch shape).
Puff, too much text, sorry!
PS. This was reported by @lufre1! With this fix, things should work on super small crops as expected now!
cc: @constantinpape
=> Minor update to segmentation dataset sample count calculation
