constantinpape/torch-em

torch_em/trainer/default_trainer.py, torch_em/trainer/tensorboard_logger.py, torch_em/trainer/wandb_logger.py
wandb has the nice functionality of generating run names...  This PR supports this in the default trainer with name=None
=> Gen trainer name

torch_em/trainer/wandb_logger.py
wandb_logger was outdated I assume
also does not expect "WANDB_MODE" to be set anymore
=> fix make_grid_image returns tuple

test/data/test_dataset_wrapper.py, torch_em/data/__init__.py, torch_em/data/dataset_wrapper.py
not entirely sure if this DatasetWrapper is of general interest or just another case for a ubiquitous utils.py ... 
the simple idea is to add a callback on whatever a given dataset returns
=> add DatasetWrapper

torch_em/trainer/wandb_logger.py
=> fix mode argument (not called wandb_mode)

torch_em/data/datasets/cremi.py, torch_em/segmentation.py, torch_em/trainer/default_trainer.py, torch_em/trainer/wandb_logger.py
This PR fixes that the changes for loader_kwargs did not spread in all the needed places
and adds them to the training checkpoint
also adds init_data logging for WandbLogger
=> Expose and fix logger kwargs 

torch_em/trainer/wandb_logger.py
=> add config kwarg to WandbLogger

torch_em/shallow2deep/shallow2deep_model.py
I added the boolean we discussed. Works correctly in my code and boosts the speed almost 5x
=> add boolean to set ilastik threads to 0

torch_em/shallow2deep/pseudolabel_training.py, torch_em/util/debug.py
you mentioned once that this could be helpful
=> add plt functionality for check_loader

.github/workflows/test.yaml, torch_em/data/datasets/__init__.py, torch_em/data/datasets/plantseg.py, torch_em/shallow2deep/prepare_shallow2deep.py, torch_em/shallow2deep/shallow2deep_dataset.py, torch_em/shallow2deep/transform.py
=> Implement shallow2deep for multi-class predictions

torch_em/data/raw_dataset.py, torch_em/data/segmentation_dataset.py
to load models from checkpoints that have been moved.
=> Enable partial deserialization of raw and segmentation dataset

test/trainer/test_default_trainer.py, torch_em/data/raw_dataset.py, torch_em/data/segmentation_dataset.py
=> Deserialize ROI Wrapper WIP

experiments/shallow2deep/em-mitochondria/evaluation.py, experiments/shallow2deep/em-mitochondria/train_mitoem_2d.py, experiments/shallow2deep/em-mitochondria/train_mitoem_3d.py, experiments/shallow2deep/em-mitochondria/train_mitoem_direct.py, torch_em/data/datasets/mitoem.py, torch_em/shallow2deep/prepare_shallow2deep.py
@k-dominik, I had a look at the features now, and they are fairly close to ilastik settings already, so I only changed the `outerScale` for the structure tensor.
=> Update s2d features, extend mito-enhancer training

experiments/shallow2deep/em-mitochondria/README.md, experiments/shallow2deep/em-mitochondria/check_predictions.py, experiments/shallow2deep/em-mitochondria/evaluation.py, experiments/shallow2deep/em-mitochondria/export_enhancer.py, torch_em/shallow2deep/shallow2deep_eval.py, torch_em/util/modelzoo.py
=> Extend shallow2deep experiments

experiments/neuron-segmentation/axondeepseg/check_data.py, experiments/neuron-segmentation/axondeepseg/export_bioimageio_model.py, experiments/neuron-segmentation/axondeepseg/train_semantic_network.py, torch_em/data/datasets/__init__.py, torch_em/data/datasets/axondeepseg.py, torch_em/data/datasets/util.py, torch_em/transform/label.py
=> Add axon myelin training

test/transform/test_augmentations.py
TODO add test for:
- elastic trafos 2d
- elastic trafos 3d
- interpolation functionality (make sure labels are nearest interpolated!)
=> Add tests for augmentations

torch_em/shallow2deep/prepare_shallow2deep.py
I added another sampling strategy as an assitional baseline. It is the same as the traditional approach (dense) but can accumulate training points over stages.
=> add dense accumulate as additional baseline

experiments/probabilistic_domain_adaptation/livecell/punet_adamatch.py, experiments/probabilistic_domain_adaptation/livecell/punet_adamt.py, experiments/probabilistic_domain_adaptation/livecell/punet_fixmatch.py
Minor changes to the prediction and evaluation of:
- FixMatch
- AdaMT
- AdaMatch
=> Update Prediction Functions for PUNet Domain Adaptation Setups

torch_em/data/datasets/__init__.py, torch_em/data/datasets/tissuenet.py
- Dataloader for the TissueNet dataset (WIP)
=> TissueNet Dataloader

torch_em/util/debug.py
- Added an optional path variable which would save the plots  using matplotlib when provided
=> Update check_loader to save plots

scripts/datasets/check_sponge_em.py, torch_em/data/datasets/__init__.py, torch_em/data/datasets/sponge_em.py, torch_em/data/datasets/uro_cell.py
=> Implement sponge em dataset

torch_em/model/unetr.py
- Updating the inputs from the encoder being passed to the decoder
=> Minor Fix to UNETR Decoder

scripts/datasets/check_pannuke.py, torch_em/data/datasets/pannuke.py
- Removed loader checking scripts from pannuke dataset script.
- Added a `check_pannuke.py` script in the `scripts` directory.
=> Add PanNuke Check Script

torch_em/data/datasets/neurips_cell_seg.py
- Added description for the assertion errors while path isn't found for the expected neurips directories
- Added details about where the data is publicly available in dataset docstrings
=> Raise download prompt - NeurIPS CellSeg

experiments/vision-transformer/unetr/livecell/README.md, experiments/vision-transformer/unetr/livecell/check_hv_segmentation.py, experiments/vision-transformer/unetr/livecell/common.py, experiments/vision-transformer/unetr/livecell/livecell_all_hovernet.py
WIP - This PR takes care of the UNETR experiments with distance maps (inspired from HoVerNet)
=> Add LIVECell Distance Map Experiments

scripts/datasets/check_nuc_mm.py, torch_em/data/datasets/nuc_mm.py, torch_em/data/datasets/util.py
This PR addresses updating the function to download google drive files using `gdown`. With the current updates, we can now download files from google drive without much hassle.
=> Update NucMM dataset

torch_em/data/datasets/mitoem.py
This PR fixes the download path to the rat volume for now.
=> Fix mitoem rat volume download

environment_cpu.yaml, environment_gpu.yaml, test/util/test_modelzoo.py, torch_em/util/modelzoo.py
The new release of bioimageio.core is there, but apparently not yet on conda-forge.
=> Bump bioimageio dependency

scripts/datasets/check_drive.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/drive.py, torch_em/transform/generic.py
This is a dataset for retinal vessel segmentation in fundus images.
=> Add DRIVE dataset

scripts/datasets/check_papila.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/papila.py
This is a dataset for optic cup and optic disc segmentation in fundus images.
=> Add Papila dataset

scripts/datasets/check_busi.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/busi.py
This is segmentation of breast cancer in ultrasound images. This is good to go from my side. Thanks!
=> Add BUSI dataset

notebooks/README.md
We will point to the doc website later once we create it, for now updating this to the correct spot.
=> Update dataset doc path

scripts/datasets/medical/check_sa_med2d.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/sa_med2d.py, torch_em/data/datasets/util.py, torch_em/segmentation.py, torch_em/transform/generic.py
This is a segmentation dataset for 2d images from various modalities for different tasks.
=> Add SA-Med2D-20M dataset

scripts/datasets/medical/check_osic_pulmofib.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/osic_pulmofib.py, torch_em/data/datasets/util.py
This is a dataset for lung, heart and trachea segmentation in CT scans.
=> Add OSIC Pulmonary Fibrosis dataset

torch_em/data/datasets/medical/sa_med2d.py, torch_em/data/datasets/util.py, torch_em/segmentation.py
Added an additional logic to choose a fraction of samples per dataset for segmentation, expect the datasets with a small size already.
=> Minor update SA-Med2d 20M dataset

scripts/datasets/medical/check_cholecseg8k.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/cholecseg8k.py
Segmentation of organs and instruments in endoscopy
=> Add CholecSeg8k dataset

scripts/datasets/medical/check_cbis_ddsm.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/cbis_ddsm.py
This is a dataset for segmentation of calcification and mass segmentation in mammography. Would be relevant for some OOD investigation. This is GTG from my side.
=> Add CBIS DDSM dataset

scripts/datasets/medical/check_dca1.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/dca1.py
Segmentation of vessels in x-ray angiography images.
=> Add DCA1 dataset

scripts/datasets/medical/check_spider.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/spider.py
Vertebrae segmentation in MRI series.
=> Add SPIDER dataset

torch_em/data/sampler.py
=> Mininstancesampler update

torch_em/data/datasets/util.py
=> Minor fix to resize transform for inputs

torch_em/data/datasets/light_microscopy/gonuclear.py
@constantinpape,
Added the possibility of the usual function to return different target types (eg. binary labels, etc). Should be GTG from my side!
=> Update GoNuclear dataset for returning different target types

torch_em/data/datasets/light_microscopy/gonuclear.py
@constantinpape 
Spotted the following (already discussed) issues and fixed them:
- Cell labels for one sample were flipped around, fixed them in the data preprocessing stage.
- Removed the image artifacts in last slices for two samples (in both cell and nuclei images)
I visualized the fixed volumes, looks good to me. Thanks!
=> Remove artifacts in volumes and minor fix to cell labels for GoNuclear

scripts/datasets/light_microscopy/check_plantseg.py, torch_em/data/datasets/light_microscopy/plantseg.py
Fixes https://github.com/constantinpape/torch-em/issues/341
=> Fix plantseg volumes - remove slices with artifacts

scripts/datasets/light_microscopy/check_dic_hepg2.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/dic_hepg2.py
Spotted this dataset recently in https://doi.org/10.1016/j.compbiomed.2024.109151. The dataset looks like something we can use for cell instance segmentation in DIC images.
It's GTG from my side. Thanks!
=> Add DIC HepG2 dataset

scripts/datasets/light_microscopy/check_hpa.py, torch_em/data/datasets/light_microscopy/hpa.py, torch_em/util/image.py
Takes care of https://github.com/constantinpape/torch-em/issues/350.
I made a minor addition to the way we treat multiple groups (i.e. `raw_key` / `label_key`) passed by the user and then likewise stack inputs from multiple groups. Let me know if you think there is a better way to handle this.
=> Update design for storing input channels in HPA dataset

torch_em/data/datasets/electron_microscopy/platynereis.py
Superseeds https://github.com/constantinpape/torch-em/pull/295.
This PR ensures to pass the `rois` argument to the dataset. GTG from my side!
=> Add rois back to dataset kwargs in Platynereis (Cilia)

torch_em/data/datasets/light_microscopy/deepbacs.py
This PR fixes minor issues in the docstring and updates the `get_deepbacs_data` function name to match the dataset name. GTG from my side!
=> Minor updates to DeepBacs dataset

torch_em/data/datasets/light_microscopy/tissuenet.py
This PR adds the function `get_tissuenet_data` to make the data unzipping process exclusive (i.e. to extend support for verifying the data's existence exclusively without touching the dataset). GTG from my side!
=> Minor update to TissueNet dataset

torch_em/data/datasets/light_microscopy/ctc.py, torch_em/data/datasets/light_microscopy/orgasegment.py
This PR adds docstring to the functions in OrgaSegment dataset. GTG from my side!
=> Minor updates to OrgaSegment dataset

torch_em/data/datasets/electron_microscopy/asem.py, torch_em/data/datasets/electron_microscopy/axondeepseg.py
This PR moves the download scripts for ASEM to `get_asem_data` and adds docstrings to relevant functions. GTG from my side!
=> Update ASEM dataset

torch_em/data/datasets/histopathology/bcss.py, torch_em/data/datasets/histopathology/lizard.py, torch_em/data/datasets/histopathology/monusac.py, torch_em/data/datasets/histopathology/monuseg.py, torch_em/data/datasets/histopathology/pannuke.py, torch_em/data/datasets/light_microscopy/covid_if.py
This PR adds `get_<DATASET>_paths` functionality to histopathology datasets. It's GTG from my side!
=> Add function to return input paths in histopathology datasets

scripts/datasets/medical/check_segthy.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/segthy.py
This PR adds SegThy dataset for thyroid segmentation in MRI and US dataset. GTG from my side!
=> Add SegThy dataset

scripts/datasets/medical/check_leg_3d_us.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/leg_3d_us.py
This PR adds LEG 3D US dataset for leg muscle segmentation in 3d ultrasound volumes. GTG from my side!
=> Add LEG 3D US dataset

scripts/datasets/medical/check_panorama.py, torch_em/data/datasets/light_microscopy/cellpose.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/panorama.py
This PR adds large dataset, PANORAMA - focused on segmentation of pancreatic lesions and some other structures in CT scans. Comes from the ongoing PANORAMA challenge: https://panorama.grand-challenge.org/.
=> Add PANORAMA dataset

scripts/datasets/medical/check_lgg_mri.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/lgg_mri.py
This PR adds LGG MRI dataset for glioma segmentation in brain (FLAIR) MRI scans. GTG from my side!
=> Add LGG MRI dataset

scripts/datasets/medical/check_oasis.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/lgg_mri.py, torch_em/data/datasets/medical/oasis.py
This PR adds OASIS dataset for tissue and anatomical segmentation in brain T1 MRI scans. GTG from my side!
=> Add OASIS dataset

torch_em/data/datasets/electron_microscopy/platynereis.py
This PR moves template filenames (for calculating rois out of volumes) to a global variable, to avoid passing them per dataset. GTG from my side!
=> Move platynereis file templates to global dict

torch_em/data/raw_dataset.py, torch_em/util/__init__.py, torch_em/util/util.py
@constantinpape 
added the ensure patch shape for raw dataset without labels
=> 378 add ensuring patch shape for raw dataset

scripts/datasets/light_microscopy/check_usiigaci.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/usiigaci.py
This PR adds Usiigaci dataset, contains annotations for cell segmentation in phase contrast microscopy images. GTG from my side!
=> Add Usiigaci dataset

scripts/datasets/light_microscopy/check_cartocell.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/cartocell.py
This PR adds CartoCell dataset, for cell instance segmentation in epithelial cysts. GTG from my side!
=> Add CartoCell dataset

doc/datasets_and_dataloaders.md
This PR makes minor changes to the datasets and dataloaders doc. GTG from my side!
=> Update documentation for dataset and dataloaders

torch_em/data/datasets/util.py
This PR adds minor updates to process output while downloading files from google drive. I'll go ahead and merge this.
=> Minor update to process outputs for gdrive download

torch_em/data/datasets/light_microscopy/plantseg.py
This PR takes care of a minor fix to `get_plantseg_paths`. GTG from my side!
=> Fix plantseg get paths

scripts/datasets/light_microscopy/check_vicar.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/vicar.py
This PR adds VICAR dataset (spotted this at I2K ;)) for cell segmentation in quantitative phase microscopy images. GTG from my side!
=> Add VICAR dataset

scripts/datasets/light_microscopy/check_arvidsson.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/arvidsson.py
This PR adds a new dataset for nuclei segmentation in high-content fluorescence microscopy images (spotted this in I2K as well). GTG from my side!
=> Add Arvidsson dataset

scripts/datasets/histopathology/check_srsanet.py, torch_em/data/datasets/histopathology/__init__.py, torch_em/data/datasets/histopathology/srsanet.py
This PR adds SRSA-Net dataset, for nuclei segmentation in IHC stained histology images. GTG from my side!
=> Add SRSA-Net dataset

scripts/datasets/light_microscopy/check_ifnuclei.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/ifnuclei.py
This PR adds dataset for nuclei segmentation in fluorescence microscopy images. GTG from my side!
=> Add IFNuclei dataset

scripts/datasets/histopathology/check_tnbc.py, torch_em/data/datasets/histopathology/__init__.py, torch_em/data/datasets/histopathology/tnbc.py
This PR adds histopathology dataset for nuclei segmentation. GTG from my side!
=> Add TNBC dataset

scripts/datasets/medical/check_palm.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/palm.py
This PR adds PALM dataset, for optic disc segmentation in fundus images. GTG from my side!
=> Add PALM dataset

scripts/datasets/medical/check_ct_cadaiver.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/chaos.py, torch_em/data/datasets/medical/ct_cadaiver.py, torch_em/data/segmentation_dataset.py
This PR adds cadaiver dataset, for vertebrae segmentation in CT scans. GTG from my side!
=> Add CadAIver dataset

scripts/datasets/medical/check_motum.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/motum.py
This PR adds motum dataset, for tumor segmentation in brain MRIs. GTG from my side!
=> Add MOTUM dataset

scripts/datasets/light_microscopy/check_blastospim.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/blastospim.py
This PR adds a microscopy data for 3d nucleus segmentation in mouse embryos. GTG from my side!
=> Add BlastoSPIM dataset

torch_em/util/modelzoo.py
Fixes https://github.com/constantinpape/torch-em/issues/227
=> Minor fix to enabling both quote types

scripts/datasets/light_microscopy/check_segpc.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/cellpose.py, torch_em/data/datasets/light_microscopy/segpc.py, torch_em/segmentation.py
This PR adds SegPC dataset for plasma cell (and nuclei) segmentation. I saw UN-SAM perform experiments on this, but this isn't histopathology images (we might profit from some analysis on this later on anyways). GTG from my side!
=> Add SegPC dataset

scripts/datasets/histopathology/check_puma.py, torch_em/data/datasets/histopathology/__init__.py, torch_em/data/datasets/histopathology/puma.py
This PR adds a new H&E stained histopathology dataset for nuclei and tissue segmentation. GTG from my side!
=> Add PUMA dataset

scripts/datasets/histopathology/check_nuinsseg.py, torch_em/data/datasets/histopathology/__init__.py, torch_em/data/datasets/histopathology/nuinsseg.py
This PR adds NuInsSeg, dataset for nuclei segmentation in H&E stained images. GTG from my side!
=> Add NuInsSeg dataset

scripts/datasets/histopathology/check_janowczyk.py, torch_em/data/datasets/histopathology/__init__.py, torch_em/data/datasets/histopathology/janowczyk.py, torch_em/data/datasets/util.py
This PR adds a dataset for nuclei, epithelium and tubule segmentation in H&E stained histopathology images. GTG from my side!
=> Add Janowczyk dataset

scripts/datasets/histopathology/check_cpm.py, torch_em/data/datasets/histopathology/__init__.py, torch_em/data/datasets/histopathology/cpm.py, torch_em/data/datasets/light_microscopy/cellpose.py
This PR adds CPM dataset, for nuclei segmentation in H&E stained histopathology images. GTG from my side!
=> Add CPM dataset

torch_em/util/prediction.py
@constantinpape 
related to https://github.com/computational-cell-analytics/synapse-net/issues/53
=> exchanged napari progress with tqdm

torch_em/data/datasets/medical/leg_3d_us.py
This PR removes irrelevant label annotations outside the scope of known annotation ids. I'll go ahead and merge this once the tests pass!
=> Remove other irrelevant labels for LEG 3D US dataset

scripts/datasets/histopathology/check_monusac.py, torch_em/data/datasets/histopathology/monusac.py
This PR takes care of a minor fix to preprocessing assumption. I'll go ahead and merge this once the tests pass!
=> Minor fix to preprocessing MoNuSaC

torch_em/data/datasets/histopathology/puma.py
This PR takes care of a corner case for create hierarchies in storing inputs in h5 files. I'll go ahead and merge this once the tests pass!
=> Minor fix to PUMA dataset

torch_em/data/datasets/medical/cbis_ddsm.py
This PR makes a minor fix consistent across all data splits (I missed out on making this update for the test split before). I'll go ahead and merge this once the tests pass!
=> Minor fix to filtering mismatching image-label pairs

scripts/datasets/histopathology/check_nuclick.py, torch_em/data/datasets/histopathology/__init__.py, torch_em/data/datasets/histopathology/nuclick.py
This PR adds an IHC-stained histopathology dataset for lymphocyte segmentation. GTG from my side!
=> Add NuClick dataset

scripts/datasets/light_microscopy/check_cellbindb.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/cellbindb.py, torch_em/data/datasets/light_microscopy/cellpose.py
This PR adds a new dataset for cell segmentation across different modalities (a really cool collection tbh) and a total of ~1000 image-label pairs. GTG from my side!
=> Add CellBinDB dataset

scripts/datasets/light_microscopy/check_dsb.py, torch_em/data/datasets/light_microscopy/dsb.py
This PR adds the full set of the DSB dataset. I did some refactoring in favor of as much flexibility in multiple combinations. GTG from my side!
=> Add full set of DSB dataset

scripts/datasets/light_microscopy/check_brifiseg.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/brifiseg.py
This PR adds a brightfield image dataset for nuclei segmentation. GTG from my side!
PS. It's a nice dataset but not of any immediate benefit to us from what I can think of
=> Add BriFiSeg dataset

scripts/datasets/light_microscopy/check_yeaz.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/yeaz.py
This PR adds a new dataset for yeast cell segmentation in BF and PhC microscopy images. GTG from my side!
PS. The PhC data has 2d+t images (might come handy in near future).
=> Add YeaZ dataset

scripts/datasets/light_microscopy/check_deepseas.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/deepseas.py, torch_em/data/datasets/util.py
This PR adds a phase contrast microscopy dataset for cell segmentation (has data for tracking as well, might be relevant for us in near future). GTG from my side!
PS. I spotted it via another publication. I couldn't find a connected publication for this dataset besides the official GitHub repo and website!
=> Add DeepSeas dataset

scripts/datasets/histopathology/check_cpm.py, scripts/datasets/histopathology/check_janowczyk.py, scripts/datasets/histopathology/check_puma.py, scripts/datasets/histopathology/check_tnbc.py, torch_em/data/datasets/histopathology/cpm.py, torch_em/data/datasets/histopathology/janowczyk.py, torch_em/data/datasets/histopathology/puma.py, torch_em/data/datasets/histopathology/tnbc.py
Superseeds and closes https://github.com/constantinpape/torch-em/pull/443.
This PR ensures that all datasets have exclusive train-val-test splits (thanks to @titusgriebel for taking care of this).
I am pending a few minor touch-ups. I'll merge it once I am done with them as well!
=> Ad explicit splits for histopathology datasets

scripts/datasets/histopathology/check_cpm.py, torch_em/data/datasets/histopathology/cpm.py, torch_em/data/datasets/histopathology/cryonuseg.py, torch_em/data/datasets/histopathology/janowczyk.py, torch_em/data/datasets/histopathology/lizard.py, torch_em/data/datasets/histopathology/lynsec.py, torch_em/data/datasets/histopathology/monusac.py, torch_em/data/datasets/histopathology/monuseg.py, torch_em/data/datasets/histopathology/nuclick.py, torch_em/data/datasets/histopathology/nuinsseg.py, torch_em/data/datasets/histopathology/pannuke.py, torch_em/data/datasets/histopathology/puma.py, torch_em/data/datasets/histopathology/srsanet.py, torch_em/data/datasets/histopathology/tnbc.py
This PR contains resize transformations for histopathology images (as an optional argument). This gives us the flexibility to train on consistent spatial shapes. I'll go ahead and merge this once the tests pass!
cc: @constantinpape (I would like to discuss something on this lines for our experiments with you tomorrow, if I can remember hehe)
=> Add support for resizing inputs to patch shape

scripts/datasets/light_microscopy/check_cvz_fluo.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/cvz_fluo.py
This PR adds a new dataset for cell and nuclei segmentation in fluorescence microscopy images. GTG from my side!
PS: @constantinpape: This dataset is actually very good with very nice annotation tbh. I was too tempted to let this slide. Thanks for reminding. I will work on automating downloading via Synapse later (I found a tutorial on their documentation which seems (and is) super easy actually).
=> Add CVZ Fluo dataset

torch_em/data/datasets/histopathology/cpm.py
This PR removes a minor debugging script from the dataset. I'll merge this once the tests pass!
=> Remove minor debugging artifact in CPM dataset

scripts/datasets/medical/check_papila.py, torch_em/data/datasets/medical/papila.py
This PR adds splits to papila dataset. GTG from my side!
=> Add data splits to papila dataset

scripts/datasets/medical/check_psfhs.py, torch_em/data/datasets/medical/psfhs.py
This PR adds splits for PSFHS dataset. GTG from my side!
=> Add data splits for PSFHS dataset

scripts/datasets/medical/check_amd_sd.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/amd_sd.py, torch_em/data/datasets/medical/amos.py
This PR adds a new OCT dataset for multi-class lesion segmentation. GTG from my side!
=> Add AMD-SD dataset

scripts/datasets/medical/check_mice_tumseg.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/mice_tumseg.py
This PR adds a new microCT data for tumor segmentation in mice. GTG from my side!
=> Add Mice TumSeg data

torch_em/data/datasets/medical/jsrt.py
This PR adds the resize inputs argument for the JSRT dataset. I'll merge this once the tests pass!
=> Add resize inputs for JSRT data

scripts/datasets/light_microscopy/check_bitdepth_nucseg.py, scripts/datasets/light_microscopy/check_cellpose.py, scripts/datasets/light_microscopy/check_ctc.py, scripts/datasets/light_microscopy/check_cvz_fluo.py, scripts/datasets/light_microscopy/check_deepbacs.py, scripts/datasets/light_microscopy/check_dynamicnuclearnet.py, scripts/datasets/light_microscopy/check_embedseg.py, scripts/datasets/light_microscopy/check_ifnuclei.py, scripts/datasets/light_microscopy/check_omnipose.py, scripts/datasets/light_microscopy/check_orgasegment.py, scripts/datasets/light_microscopy/check_tissuenet.py, scripts/datasets/light_microscopy/check_yeaz.py, torch_em/data/datasets/light_microscopy/bitdepth_nucseg.py, torch_em/data/datasets/light_microscopy/cellpose.py, torch_em/data/datasets/light_microscopy/ctc.py, torch_em/data/datasets/light_microscopy/dsb.py, torch_em/data/datasets/light_microscopy/dynamicnuclearnet.py, torch_em/data/datasets/light_microscopy/ifnuclei.py, torch_em/data/datasets/light_microscopy/omnipose.py, torch_em/data/datasets/light_microscopy/orgasegment.py, torch_em/data/datasets/light_microscopy/yeaz.py
This PR takes care of a minor refactor to LM datasets (still a WIP). I'll merge this once I have ensured all datasets have the data splits as expected!
=> Minor refactor to LM datasets 

torch_em/data/datasets/light_microscopy/tissuenet.py
This PR updates the three-channel logic for TissueNet dataset. The new logic states the channels as follows: (cell channel, nucleus channel, channel with zeros). GTG from my side!
=> Minor update to three-channel logic in tissuenet

torch_em/data/datasets/light_microscopy/livecell.py
This PR fixes minor typos in LIVECell dataset. I'll go ahead and merge this once the tests pass!
=> Fix typo in LIVECell dataset

torch_em/data/concat_dataset.py, torch_em/data/dataset_wrapper.py, torch_em/data/image_collection_dataset.py, torch_em/data/pseudo_label_dataset.py, torch_em/data/raw_dataset.py, torch_em/data/raw_image_collection_dataset.py, torch_em/data/sampler.py, torch_em/data/segmentation_dataset.py, torch_em/loss/dice.py, torch_em/multi_gpu_training.py, torch_em/segmentation.py, torch_em/trainer/default_trainer.py, torch_em/transform/raw.py, torch_em/util/grid_search.py, torch_em/util/prediction.py, torch_em/util/segmentation.py, torch_em/util/util.py, torch_em/util/validation.py
This PR adds docstring and type annotations to some other functionalities. GTG from my side!
=> Add docstring to other functionalities

torch_em/data/datasets/histopathology/cpm.py, torch_em/data/datasets/histopathology/janowczyk.py, torch_em/data/datasets/histopathology/puma.py, torch_em/data/datasets/histopathology/tnbc.py
This PR adds a minor update to informing users about creating new split files. I'll go ahead and merge this once the tests pass!
=> Minor update to inform about creating custom data splits

scripts/datasets/histopathology/check_cryonuseg.py, torch_em/data/datasets/histopathology/cryonuseg.py
This PR superseeds and closes https://github.com/constantinpape/torch-em/pull/471.
=> Add custom splits for CryoNuSeg dataset

torch_em/data/datasets/electron_microscopy/mitoem.py
This PR takes care of a minor fix in MitoEM dataset. I'll merge this once the tests pass!
=> Minor fix to argument positions in MitoEM dataset

scripts/datasets/electron_microscopy/check_aimseg.py, torch_em/data/datasets/electron_microscopy/__init__.py, torch_em/data/datasets/electron_microscopy/aimseg.py, torch_em/data/datasets/electron_microscopy/emneuron.py
This PR adds AimSeg, a TEM data with semantic and instance segmentation targets for myelinated axons! GTG from my side!
=> Add AimSeg data

scripts/datasets/medical/check_dsad.py, scripts/datasets/medical/check_ircadb.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/dsad.py, torch_em/data/datasets/medical/idrid.py, torch_em/data/datasets/medical/ircadb.py
=> Add new medical imaging datasets

torch_em/data/datasets/medical/dsad.py
=> Minor fix to DSAD data download

torch_em/data/datasets/medical/amd_sd.py
=> Fix return type for AMD SD data

torch_em/data/datasets/medical/leg_3d_us.py
=> Fix citation details for LEG 3D US

torch_em/util/prediction.py
The prediction of the distance U-Net using a halo is parallelized using a list with block indexes as an input.
Functional implementation
=> Parallelization of prediction blocks

torch_em/data/datasets/light_microscopy/livecell.py
This PR updates instructions on how to install `pycocotools` if not found. GTG from my side!
=> Minor update to installation instruction for pycocotools

torch_em/data/datasets/electron_microscopy/lucchi.py
I'll merge this once the tests pass!
=> Minor fix to lucchi data download

scripts/datasets/light_microscopy/check_nis3d.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/mouse_embryo.py, torch_em/data/datasets/light_microscopy/nis3d.py
This PR adds a new fluo data for nucleus segmentation. GTG from my side!
=> Add NIS3d dataset

scripts/datasets/electron_microscopy/check_betaseg.py, torch_em/data/datasets/electron_microscopy/__init__.py, torch_em/data/datasets/electron_microscopy/betaseg.py, torch_em/data/datasets/electron_microscopy/cellmap.py
WIP!
Once this is finalized, will close https://github.com/constantinpape/torch-em/issues/462.
=> Add BetaSeg data

scripts/datasets/light_microscopy/check_pnas_arabidopsis.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/pnas_arabidopsis.py
=> Add PNAS Arabidopsis data

scripts/datasets/light_microscopy/check_organoid.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/organoid.py
This PR adds the OrganoID data for organoid segmentation. It is a pretty cool data, because some treatment data has tracking annotations! ;)
=> Add OrganoID data

scripts/datasets/light_microscopy/check_aisegcell.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/aisegcell.py
=> Add aiSEGcell data

torch_em/data/datasets/medical/amos.py
Super tiny update, I'll go ahead and merge this!
=> Minor update to remove unnecessary files in AMOS data folder

torch_em/data/sampler.py
Okay I managed to figure out why my trainings broke :')
It was my mistake in formulating the logic. This is fixed now. I will go ahead and merge this!
=> Fix custom semantic ids sampler

torch_em/data/datasets/medical/curvas.py
This bothered me for a while now. The data loading was embarassingly slow (and there's just unnecessary precision in the data, which makes loading such large volumes a nightmare).
Well, this is fixed now (and we have an efficient data loading) :)
GTG from my side. I will go ahead and merge this!
=> Make CURVAS data loading efficient

torch_em/data/datasets/histopathology/puma.py
I will go ahead and merge this!
=> Fix PUMA dataset default arguments and make missing module error more verbose

scripts/datasets/medical/check_fundus_avseg.py, torch_em/data/datasets/medical/__init__.py, torch_em/data/datasets/medical/fundus_avseg.py
WIP!
This PR adds artery-vein segmentation data of fundus images.
I will come back to this and finalize it tomorrow!
=> Add Fundus AVSeg data

scripts/datasets/light_microscopy/check_bac_mother.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/bac_mother.py
This PR adds the BacMother dataset, from the CellTRACTR paper.
NOTE: It has bacteria videos with segmentation and tracking annotations, all in CTC format!
GTM from my side!
=> Add BacMother data

scripts/datasets/light_microscopy/check_celegans_atlas.py, torch_em/data/datasets/light_microscopy/__init__.py, torch_em/data/datasets/light_microscopy/celegans_atlas.py
This PR adds a new 3d confocal data for nucleus segmentation. GTM from my side!
=> Add CElegans Atlas data
